# -*- coding: utf-8 -*-
"""FaceMaskDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvtNjTC-Iq83omArnB6qeChbb9XpPECv
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d omkargurav/face-mask-dataset

!unzip face-mask-dataset.zip

!ls

"""**Libraries**"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.preprocessing import image

"""**2️⃣ Dataset Path**"""

DATASET_PATH = "data"

""" **3️⃣ Image Preprocessing**

"""

img_size = 224
batch_size = 32

datagen = ImageDataGenerator(
    rescale=1./255,      # normalize images
    validation_split=0.2  # 20% for validation
)

train_data = datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary',
    subset='training'
)

val_data = datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary',
    subset='validation'
)

"""**4️⃣ Build CNN Model**"""

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(img_size, img_size,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')   # binary classification
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""**5️⃣ Train the Model**"""

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

"""**6️⃣ Plot Accuracy & Loss**"""

plt.figure(figsize=(12,5))

# Accuracy
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

"""**7️⃣ Save Model**"""

model.save('face_mask_model.h5')

"""**8️⃣ Test on Single Image**"""

import matplotlib.pyplot as plt

# Replace with any image inside 'with_mask/' or 'without_mask/' folder
test_img_path = '/content/person2.jfif'

# Load image
img = image.load_img(test_img_path, target_size=(224,224))
img_array = image.img_to_array(img)/255.0
img_array_exp = np.expand_dims(img_array, axis=0)

# Predict
pred = model.predict(img_array_exp)

# Determine label
label = "No Mask ❌" if pred[0][0] > 0.5 else "with Mask 😷"

# Display image with label
plt.imshow(img)
plt.title(f"Prediction: {label}")
plt.axis('off')
plt.show()

import matplotlib.pyplot as plt

# Replace with any image inside 'with_mask/' or 'without_mask/' folder
test_img_path = '/content/person1.jfif'

# Load image
img = image.load_img(test_img_path, target_size=(224,224))
img_array = image.img_to_array(img)/255.0
img_array_exp = np.expand_dims(img_array, axis=0)

# Predict
pred = model.predict(img_array_exp)

# Determine label
label = "No Mask ❌" if pred[0][0] > 0.5 else "with Mask 😷"

# Display image with label
plt.imshow(img)
plt.title(f"Prediction: {label}")
plt.axis('off')
plt.show()